Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Configure an IP and shared folders
  config.vm.network "public_network", type: "dhcp" #use_dhcp_assigned_default_route: true
  config.vm.synced_folder ".", "/vagrant"#, type: "nfs"

  # Provision the machine
  config.vm.provision "main", type: "ansible_local" do |ansible|
    ansible.playbook = "main.yml"
  end

end
